# Travis CI configuration
# see https://docs.travis-ci.com/user/languages/python

os: linux
dist: bionic

language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install .

script: python setup.py test

addons:
  postgresql: "12"
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
      - postgresql-server-dev-12

services:
  - postgresql

before_script:
  - psql -U postgres -c 'create database unittest'
