language: python
# unfortunately, Travis cannot be used to test with Python 2.4 and 2.5
python:
  - "2.6"
  - "2.7"
install:
  - pip install .
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install unittest2; fi
script: python setup.py test
addons:
  postgresql: "9.1"
services:
  - postgresql
before_script:
  - psql -U postgres -c 'create database unittest'