# Travis CI configuration
# see https://docs.travis-ci.com/user/languages/python

language: python

matrix:
  include:
    - name: Code quality tests
      env: TOXENV=flake8,docs
      python: 3.8
    - name: Unit tests with Python 3.9
      env: TOXENV=py39
      python: 3.9
    - name: Unit tests with Python 3.8
      env: TOXENV=py38
      python: 3.8
    - name: Unit tests with Python 3.7
      env: TOXENV=py37
      python: 3.7
    - name: Unit tests with Python 3.6
      env: TOXENV=py36
      python: 3.6
    - name: Unit tests with Python 3.5
      env: TOXENV=py35
      python: 3.5
    - name: Unit tests with Python 2.7
      env: TOXENV=py27
      python: 2.7

cache:
  directories:
    - "$HOME/.cache/pip"
    - "$TRAVIS_BUILD_DIR/.tox"

install:
  - pip install tox-travis

script:
  - tox -e $TOXENV

addons:
  # test with last version that still supports OIDs
  postgresql: "11"

services:
  - postgresql

before_install:
  - sudo apt-get remove -y postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo service postgresql restart 11

before_script:
  - psql -U postgres -c 'create database unittest'
