# Travis CI configuration
# see https://docs.travis-ci.com/user/languages/python

language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install .

script: python setup.py test

addons:
  postgresql: "12"
  apt:
    sources:
      - sourceline: deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main 12
        key_url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    packages:
      - postgresql-12
      - postgresql-server-dev-12

env:
  global:
  - PGPORT=5433

services:
  - postgresql

before_script:
  - echo "dbport = 5433" > tests/LOCAL_PyGreSQL.py
  - psql -U postgres -c 'create database unittest'
