name: Run PyGreSQL quality checks

on:
  push:
  pull_request:

jobs:
  checks:
    name: Quality checks run
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install tox
        run: pip install tox
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Run quality checks
        run: tox -e ruff,docs
        timeout-minutes: 5
