name: Release PyGreSQL documentation

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo apt install libpq-dev
        python -m pip install --upgrade pip
        pip install .
        pip install "sphinx>=2.4,<3"
        pip install "cloud_sptheme>=1.10,<2"
    - name: Create docs with Sphinx
      run: |
        cd docs
        make html
    - name: Deploy docs to GitHub pages
      uses: peaceiris/actions-gh-pages@v3.4.0
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_branch: gh-pages
        publish_dir: docs/_build/html
        cname: www.pygresql.org
        disable_nojekyll: true
        force_orphan: true
